# Supplementary Practice Problems

These are similar to programming problems you may encounter in the mid-terms. They are not graded but we will review them in lab sessions.

For these questions, you should try to solve the problem manually first (or at least detail out the steps if the algebra is too horrible), then use `scipy.linalg` package routine(s) to solve.

**1**. Write down the full-matrix, block matrix and outer product forms of the SVD using $\LaTeX$ in a markdown cell.

$$
A = U \Sigma V^T
$$

$$
A = \begin{bmatrix}
U_1 & U_2
\end{bmatrix}
\begin{bmatrix}
\Sigma_1 & 0\\
0 & 0
\end{bmatrix}
\begin{bmatrix}
V_1^{T}\\
V_2^{T}
\end{bmatrix}
$$

$$
A = \sum_{i=1}^k s_i u_i v_i^T
$$

**2**. Let
$$
u = \begin{bmatrix}
1 \\
2 \\
3 
\end{bmatrix}
$$
Find a non-zero vector $v$ that is orthogonal to $u$, and another non-zero vector $w$ that is orthogonal to both $u$ and $v$. Construct an orthogonal matrix $Q$ using the unit versions of $u, v, w$. What is the inverse of $Q$?

In [1]:
import numpy as np
import scipy.linalg as la
u = [1,2,3]
v = [3,0,-1]
w1 = np.cross(u,v)

In [2]:
A = np.c_[u,v]
w2 = np.array([1,0,0])
w2 = w2 - A@la.inv(A.T@A)@A.T @ w2

In [3]:
w3 = np.array([1,0,0])
sln,_,_,_ = la.lstsq(A,w3)
w3 = w3 - A@sln

In [4]:
A = np.c_[u,v,w1]
Q1 = A/np.linalg.norm(A, axis=0)
np.round(Q1 @ Q1.T, 10).astype('int')

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [5]:
Q3 = la.orth(np.c_[u,v,w3])
np.round(Q3 @ Q3.T, 10).astype('int')

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

**3**. Find a basis for the 4 fundamental spaces of $A$, where
$$
A = \begin{bmatrix}
1 & 2 & 3 & 3 \\
2 & 0 & 6 & 2 \\
3 & 4 & 9 & 7
\end{bmatrix}
$$
State the dimension of each basis, and the dimension of the space of the basis vectors.

In [6]:
A =  np.array([[1,2,3,3],[2,0,6,2],[3,4,9,7]])
U,s,Vh = la.svd(A)
eps = 1e-10
rank = sum(s>eps)
# C(A) basis
C_A = U[:,:rank]
# N(A.T) basis
N_At = U[:,rank:]
# C(A.T) basis
C_At = Vh[:rank,:].T
# N(A) basis
N_A = Vh[rank:,:].T

In [7]:
print(np.round(A.T@N_At, 10))
print(np.round(A@N_A, 10))

[[-0.]
 [-0.]
 [-0.]
 [-0.]]
[[ 0.  0.]
 [ 0. -0.]
 [ 0. -0.]]


**4**. Find the projection of
$$
b = \begin{bmatrix}
3 \\
2 \\
1
\end{bmatrix}
$$
on the column space of $A$ by using the projection matrix, where 
$$
A = \begin{bmatrix}
1 & 2 & 3 & 3 \\
2 & 0 & 6 & 2 \\
3 & 4 & 9 & 7
\end{bmatrix}
$$

In [8]:
b = np.array([3,2,1]).reshape(-1,1)
b_proj = C_A@la.inv(C_A.T@C_A)@C_A.T @ b

In [9]:
sln,_,_,_ = la.lstsq(A, b)
np.round(A@sln-b_proj, 10)

array([[ 0.],
       [ 0.],
       [ 0.]])

**5**. What is the inverse of
$$
A = \begin{bmatrix}
0 & 0 & 0 & 1 \\
0 & 0 & 1 & 0 \\
1 & 0 & 0 & 0 \\
0 & 1 & 0 & 0
\end{bmatrix}
$$

In [10]:
A = np.array([[0,0,0,1],[0,0,1,0],[1,0,0,0],[0,1,0,0]])
A.T @ A

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

**6**. Find the eigenvalues and eigenvectors of $A^TA$, and find an eigendecomposition of $A^TA = V \Lambda V^T$. Finally, construct the SVD of $A$ and use it to generate $A$
$$
A = \begin{bmatrix}
1 & 2 & 3 & 3 \\
2 & 0 & 6 & 11 \\
3 & 4 & 9 & 7 \\
4 & 4 & 4 & 4
\end{bmatrix}
$$

In [11]:
A =  np.array([[1,2,3,3],[2,0,6,11],[3,4,9,7],[4,4,4,4]])
e, vec = la.eigh(A.T@A)
e, vec = e[::-1], vec[:,::-1] # la.eigh results use ascending order 
eps = 1e-10
k = sum(np.abs(e)>eps)
# k = np.linalg.matrix_rank(A)
D, V = np.diag(e[:k]), vec[:, :k]
np.round(A.T@A - V@D@V.T, 10)

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [12]:
s = np.sqrt(e)
U = A@V@np.diag(1/s)
np.round(A-U@np.diag(s)@V.T, 10)

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

**7**. Find an orthogonal basis and the QR decomposition for
$$
A = \begin{bmatrix}
1 & 2 & 0 \\
1 & 0 & 2 \\
0 & 1 & 2
\end{bmatrix}
$$

In [13]:
A = np.array([[1,2,0],[1,0,2],[0,1,2]])
Q,R = la.qr(A)

**8**. Solve the following problem
$$
\begin{bmatrix}
1 & 2 & 3 & 3 \\
2 & 0 & 6 & 11 \\
3 & 4 & 9 & 7 \\
4 & 4 & 4 & 4
\end{bmatrix} \begin{bmatrix}
x_1 \\
x_2 \\
x_3 \\
x_4
\end{bmatrix} = \begin{bmatrix}
4 \\
3 \\
2 \\
1
\end{bmatrix}
$$
using the following factorizations
- Gaussian elimination
- LU
- LDU
- QR
- SVD

In [14]:
A = np.array([
    [1,2,3,3],
    [2,0,6,11],
    [3,4,9,7],
    [4,4,4,4]
])
b = np.array([4,3,2,1])[:,None]
sln0 = la.solve(A, b)
sln0

array([[-3.29166667],
       [ 3.33333333],
       [-1.45833333],
       [ 1.66666667]])

In [15]:
#LU
# P,L,U = la.lu(A)
# print(np.allclose(P@L@U, A))
# y = la.solve_triangular(L, P.T@b, lower=True)
# sln1 = la.solve_triangular(U,y, lower=False)
# sln1
LU, P = la.lu_factor(A)
sln1 = la.lu_solve((LU,P), b)
sln1

array([[-3.29166667],
       [ 3.33333333],
       [-1.45833333],
       [ 1.66666667]])

In [16]:
#LDU
P,L,U = la.lu(A)
D = np.diag(U)
U = U/D[:,None]
print(np.allclose(P@L@np.diag(D)@U,A))
y = la.solve_triangular(L, P.T@b, lower=True)
sln2 = la.solve_triangular(U, y/D[:,None], lower=False)
sln2

True


array([[-3.29166667],
       [ 3.33333333],
       [-1.45833333],
       [ 1.66666667]])

In [17]:
#QR
Q,R = la.qr(A)
sln3 = la.solve_triangular(R,Q.T@b, lower=False)
sln3

array([[-3.29166667],
       [ 3.33333333],
       [-1.45833333],
       [ 1.66666667]])

In [18]:
#SVD
U,s,Vt = la.svd(A)
sln4 = 1/s * Vt.T @ U.T @ b
sln4

array([[-3.29166667],
       [ 3.33333333],
       [-1.45833333],
       [ 1.66666667]])

**9**. Let $A$ be the plane spanned by the vectors

$$ v_1
\begin{bmatrix}
1 \\
0 \\
1 \\
0
\end{bmatrix}, v_2 = \begin{bmatrix}
1 \\
2 \\
3 \\
4
\end{bmatrix}
$$
What is the point on the plane nearest to the vectors $b_1$ and $b_2$.
$$
b_1 = \begin{bmatrix}
3 \\
2 \\
5 \\
4
\end{bmatrix}, b_2 = \begin{bmatrix}
3 \\
2 \\
0 \\
4
\end{bmatrix}
$$
Find the orthogonal distance from $b_1$ and $b_2$ to its nearest point.

In [19]:
A = np.c_[[1,0,1,0],[1,2,3,4]]
b1 = np.array([3,2,5,4])[:,None]
b2 = np.array([3,2,0,4])[:,None]
x1,res1,k,_ = la.lstsq(A,b1)
b1_proj = A@x1
dist1 = np.sqrt(res1)
print(b1_proj, dist1)
x2,res2,k,_ = la.lstsq(A,b2)
b2_proj = A@x2
dist2 = np.sqrt(res2)
print(b2_proj, dist2)

[[ 3.]
 [ 2.]
 [ 5.]
 [ 4.]] [  4.32199511e-16]
[[ 0.72727273]
 [ 1.54545455]
 [ 2.27272727]
 [ 3.09090909]] [ 3.37099931]


**10**. Let
$$
A = \begin{bmatrix}
1 & 2 & 3 & 3 \\
2 & 0 & 6 & 2 \\
3 & 4 & 9 & 7 \\
4 & 4 & 4 & 4
\end{bmatrix}
$$
- What is the rank of $A$
- What is the condition number of $A$?
- What is the best rank-1 and rank-2 approximation of $A$?
- What is the distance between $A$ and the best rank-1 and rank-2 approximation of $A$ using the Frobenius norm?

In [20]:
A = np.array(
    [[1,2,3,3],
     [2,0,6,2],
     [3,4,9,7],
     [4,4,4,4]]
)
k = np.linalg.matrix_rank(A)
U,s,Vt = la.svd(A)
cond = s[0]/s[-1]
print(cond)
A_rec1 = s[:1] * U[:,:1] @ Vt[:1,:]
A_rec2 = s[:2] * U[:,:2] @ Vt[:2,:]
dist1 = la.norm(A_rec1-A)
dist2 = la.norm(A_rec2-A)
print(dist1, dist2)

4.1035635177e+16
4.11783149863 1.94826022477
